name: Workflow-push

on:
  push:
jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du repo
        uses: actions/checkout@v2
      - name: Recuperation de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Execution des tests
        run: mvn test